# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'McDriveThru.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from McDonalds import Graph

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(440, 350)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1.setGeometry(QtCore.QRect(150, 170, 91, 23))
        self.btn1.setObjectName("btn1")
        self.cbx1 = QtWidgets.QComboBox(self.centralwidget)
        self.cbx1.setGeometry(QtCore.QRect(180, 100, 69, 22))
        self.cbx1.setObjectName("cbx1")
        self.cbx2 = QtWidgets.QComboBox(self.centralwidget)
        self.cbx2.setGeometry(QtCore.QRect(180, 130, 80, 22))
        self.cbx2.setObjectName("cbx2")
        self.lbl1 = QtWidgets.QLabel(self.centralwidget)
        self.lbl1.setGeometry(QtCore.QRect(150, 100, 21, 16))
        self.lbl1.setObjectName("lbl1")
        self.lbl2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl2.setGeometry(QtCore.QRect(110, 130, 61, 20))
        self.lbl2.setObjectName("lbl2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.btn1.clicked.connect(self.clicked)

        self.cbx1.addItem('Everyday')
        self.cbx1.addItem('Monday')
        self.cbx1.addItem('Tuesday')
        self.cbx1.addItem('Wednesday')
        self.cbx1.addItem('Thursday')
        self.cbx1.addItem('Friday')
        self.cbx1.addItem('Saturday')
        self.cbx1.addItem('Sunday')

        self.cbx2.addItem('Whole Day')
        self.cbx2.addItem('4am-11am')
        self.cbx2.addItem('11am-2pm')
        self.cbx2.addItem('2pm-4pm')
        self.cbx2.addItem('4pm-9pm')
        self.cbx2.addItem('9pm-12am')
        self.cbx2.addItem('12am-4am')

    
    def clicked(self):
        Graph(str(self.cbx1.currentText()), str(self.cbx2.currentText()))
        print(self.cbx1.currentText())
        print(self.cbx2.currentText())


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn1.setText(_translate("MainWindow", "Generate Graph"))
        self.lbl1.setText(_translate("MainWindow", "Day:"))
        self.lbl2.setText(_translate("MainWindow", "Time of Day:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
